### ISSUE TITLE
Adding ESLint and Prettier GitHub Actions

### ISSUE THREAD

**Issue by iamrajiv** [adityabisoi/notation-converter#13]

**Comment by iamrajiv** [comment]
@adityabisoi I want to work on this issue.

**Comment by adityabisoi** [comment]
@iamrajiv Please tell me your approach.

**Comment by iamrajiv** [comment]
@adityabisoi For ESLint I  am using this script
```yml
name: ESLint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: rm -f .yarnclean
      - run: yarn --frozen-lockfile --ignore-engines --ignore-optional --no-bin-links --non-interactive --silent --ignore-scripts --production=false
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true
      # Alternative: if you use npm instead of yarn
      # - run: npm ci --no-audit --prefer-offline
      - uses: tinovyatkin/action-eslint@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          check-name: eslint # this is the check name from above where to post annotations
``` 
and for Prettier I am using third party action https://github.com/creyD/prettier_action.
